import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-nunito)", "Nunito Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        "display-md": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        "headline-sm": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        "body-lg": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        "body-md": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        "label-bold": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        "label-md": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        caption: ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      colors: {
        primary: "#00685f",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "on-primary-container": "#f4fffc",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        secondary: "#006b5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#96f3e1",
        "on-secondary-container": "#007164",
        "secondary-fixed": "#96f3e1",
        "secondary-fixed-dim": "#7ad7c6",
        "on-secondary-fixed": "#00201b",
        "on-secondary-fixed-variant": "#005046",
        tertiary: "#525e5c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6b7775",
        "on-tertiary-container": "#f3fffc",
        "tertiary-fixed": "#d8e5e2",
        "tertiary-fixed-dim": "#bcc9c6",
        "on-tertiary-fixed": "#121e1c",
        "on-tertiary-fixed-variant": "#3d4947",
        surface: "#f5faf8",
        "surface-dim": "#d6dbd9",
        "surface-bright": "#f5faf8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f5f2",
        "surface-container": "#eaefed",
        "surface-container-high": "#e4e9e7",
        "surface-container-highest": "#dee4e1",
        "on-surface": "#171d1c",
        "on-surface-variant": "#3d4947",
        "inverse-surface": "#2c3130",
        "inverse-on-surface": "#edf2f0",
        "surface-variant": "#dee4e1",
        "surface-tint": "#006a61",
        outline: "#6d7a77",
        "outline-variant": "#bcc9c6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f5faf8",
        "on-background": "#171d1c",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
      },
      boxShadow: {
        card: "0 8px 20px 0 rgba(0, 104, 95, 0.06)",
        lift: "0 10px 34px -6px rgba(0, 104, 95, 0.14)",
        soft: "0 8px 24px -4px rgba(0, 104, 95, 0.08), 0 4px 12px -2px rgba(0, 104, 95, 0.04)",
        nav: "0 -4px 20px 0 rgba(0, 106, 97, 0.08)",
        glow: "0 12px 24px 0 rgba(0, 104, 95, 0.06)",
        ambient: "0 12px 32px -4px rgba(0, 104, 95, 0.08)",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pingSoft: {
          "0%": { transform: "scale(1)", opacity: "0.75" },
          "75%, 100%": { transform: "scale(1.4)", opacity: "0" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.5s ease-out both",
        "ping-soft": "pingSoft 1.6s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
